### ISSUE TITLE
ViaForge and MixinBooter

### ISSUE THREAD

**Issue by Yura64UA** [ViaVersion/ViaForge#103]
### General Information

configanytime, mixinbooter, betterfps, controllable, controlling, darkredstone, entityculling, fermiumasm, fermiumbooter, foamfix, fpsreducer, homoium, ksyxis, lagbgonrevived, nether api, particleculling, phosphorcrashfix, phosphor, optifine, randompatches, rawinput, spark, universaltweaks, viaforge

### Bug Description

ViaForge crashes with MixinBooter

### Steps to Reproduce

Just download both mods ig

### Expected Behavior

the game shouldn't crash when i use viaforge

**Comment by FlorianMichael** [comment]
Provide the crashlog

**Comment by Yura64UA** [comment]
[options.txt](https://github.com/user-attachments/files/16501224/options.txt)

**Comment by Yura64UA** [comment]
[latest.log](https://github.com/user-attachments/files/16501236/latest.log)

**Comment by FlorianMichael** [comment]
MixinBooter seems to complain about my mixin ``MixinGuiMainMenu``, since I don't see anything illegal/wrong in this mixin I would say it's a MixinBooter issue and would therefore recommend reporting this issue to the developers of MixinBooter.

**Comment by Yura64UA** [comment]
ok thanks
