### ISSUE TITLE
Inability to mine bamboo on 1.12 when playing on 1.14+ servers

### ISSUE THREAD

**Issue by eightyninetytwo** [ViaVersion/ViaForge#14]
When playing on a server that is running version 1.14+, you are unable to mine bamboo unless you destroy the block below what the bamboo is on, destroying the plant itself. I haven't tried this on vanilla, but on servers with anti cheat at least it replaces the sugar cane instantly after destroying it resulting in the inability for it to be mined. Not an urgent thing just thought I'd make it known in case it wasn't :)

Great mod though, love it!

**Comment by Sumandora** [comment]
Sounds like a problem with Via.

**Comment by eightyninetytwo** [comment]
> Sounds like a problem with Via.

Yeah I thought I'd let the devs know.

**Comment by MIOGMIOG** [comment]
> Sounds like a problem with Via.

In my opinion, it is enough to update via*, so I made these pull requests: [1.8.9](https://github.com/FlorianMichael/ViaForge/pull/27) and [1.12.2](https://github.com/FlorianMichael/ViaForge/pull/26)

**Comment by MIOGMIOG** [comment]
This is extremely old send this issue to [ViaBackwards issues](https://github.com/ViaVersion/ViaBackwards/issues)

**Comment by FlorianMichael** [comment]
Hello, thanks for the report! I fixed your issue in https://github.com/ViaVersion/Mappings/commit/f0d17dbc6c10a8364cd94ab7717a4f27cf222fea and https://github.com/ViaVersion/ViaBackwards/commit/ff87b1dc925c6636ea2bfdac0b770710a5e042ba in latest ViaBackwards, the next ViaForge release will contain the fix.
