### ISSUE TITLE
Opening whis error

### ISSUE THREAD

**Issue by DestiShell** [ViaVersion/ViaForge#144]
### General Information

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

### Bug Description

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

### Steps to Reproduce

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

### Expected Behavior

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

**Comment by Kichura** [comment]
1. Not a good issue template,
2. Duplicate of #94.
