### ISSUE TITLE
[FEATURE] add optional CubicChunks support for cortectly rendering 1.19 terrain on older versions

### ISSUE THREAD

**Issue by iAmInActions** [ViaVersion/ViaForge#60]
Essentially what the title says. This would also need to have a mixin that prevents the server and client from complaining about the cubicchunks mod.

**Comment by FlorianMichael** [comment]
Shouldn't it already be compatible / have you tested it?

**Comment by Sice-0** [comment]
> Shouldn't it already be compatible / have you tested it?

The same question.I cannot render the terrain below y0, and I am in the void. I've been looking through the docs and it seems viaforge is supported, but I can't be sure. Is it possible that the server is blocking it? Hope to get your help. Thanks.

**Comment by MIOGMIOG** [comment]
> > Shouldn't it already be compatible / have you tested it?
> 
> The same question.I cannot render the terrain below y0, and I am in the void. I've been looking through the docs and it seems viaforge is supported, but I can't be sure. Is it possible that the server is blocking it? Hope to get your help. Thanks.

WHAT? I never heard that Cubic Chunks supports ViaForge. Supporting it will require another translator to convert these chunk formats in real time to cubic chunks format.

**Comment by FlorianMichael** [comment]
I won't implement support for newer world generation/height or general world changes since it would require a lot modification in Via* to be able to do this, if you want newer features, use newer versions.
