### ISSUE TITLE
Can't click viaforge button

### ISSUE THREAD

**Issue by yourfatherme** [ViaVersion/ViaForge#62]
When I use the liquidbounce client,the button of liquidbounce covers the button of viaforge, I hope to customize the position of the button(English is not my native language, so I used a translator for some words

**Comment by allinkdev** [comment]
> When I use the liquidbounce client,the button of liquidbounce covers the button of viaforge, I hope to customize the position of the button(English is not my native language, so I used a translator for some words

ViaFabricPlus has an option in Settings to customise the position of the button in the multiplayer screen. Please disable LiquidBounce first if you're unable to access the ViaFabricPlus button.

1. Click the button
![image](https://github.com/FlorianMichael/ViaForge/assets/44676012/24430d4a-53a2-4f9a-ac8a-972bc0722905)

2. Click "Settings"
![image](https://github.com/FlorianMichael/ViaForge/assets/44676012/4f8b1c3b-c40e-46cc-a010-33f002db809a)

3. Click "Main Button Orientation", and keep clicking until it shows a position that is most favourable for your use-case.
![image](https://github.com/FlorianMichael/ViaForge/assets/44676012/25ec5ab6-4919-4187-b62d-1f7bf0ffe888)

**Comment by yourfatherme** [comment]
> > 当我使用liquidbounce客户端时，liquidbounce的按钮覆盖了viaforge的按钮，我希望自定义按钮的位置（英语不是我的母语，所以我使用了一些单词的翻译器
> 
> ViaFabricPlus 在“设置”中有一个选项，用于自定义按钮在多人游戏屏幕中的位置。如果您无法访问 ViaFabricPlus 按钮，请先禁用 LiquidBounce。
> 
> 1. 点击“ViaFabricPlus”
>    ![图像](https://user-images.githubusercontent.com/44676012/238002868-24430d4a-53a2-4f9a-ac8a-972bc0722905.png)
> 2. 点击“设置”
>    ![图像](https://user-images.githubusercontent.com/44676012/238002958-4f8b1c3b-c40e-46cc-a010-33f002db809a.png)
> 3. 单击“主按钮方向”，然后继续单击，直到它显示最适合您的用例的位置。
>    ![图像](https://user-images.githubusercontent.com/44676012/238003083-25ec5ab6-4919-4187-b62d-1f7bf0ffe888.png)

But my liquidbounce is suitable for 1.12.2, but this version does not have Fabric

**Comment by allinkdev** [comment]
> > > 当我使用liquidbounce客户端时，liquidbounce的按钮覆盖了viaforge的按钮，我希望自定义按钮的位置（英语不是我的母语，所以我使用了一些单词的翻译器
> > 
> > 
> > ViaFabricPlus 在“设置”中有一个选项，用于自定义按钮在多人游戏屏幕中的位置。如果您无法访问 ViaFabricPlus 按钮，请先禁用 LiquidBounce。
> > 
> > 1. 点击“ViaFabricPlus”
> >    ![图像](https://user-images.githubusercontent.com/44676012/238002868-24430d4a-53a2-4f9a-ac8a-972bc0722905.png)
> > 2. 点击“设置”
> >    ![图像](https://user-images.githubusercontent.com/44676012/238002958-4f8b1c3b-c40e-46cc-a010-33f002db809a.png)
> > 3. 单击“主按钮方向”，然后继续单击，直到它显示最适合您的用例的位置。
> >    ![图像](https://user-images.githubusercontent.com/44676012/238003083-25ec5ab6-4919-4187-b62d-1f7bf0ffe888.png)
> 
> But my liquidbounce is suitable for 1.12.2, but this version does not have Fabric You can also use a compromise solution, please tell me how to keep the selected version I need to use 1.8.8

You need Fabric in order to use ViaFabricPlus. [LiquidBounce Nextgen](https://github.com/CCBlueX/LiquidBounce) supports 1.19.4, which is also the version of Minecraft ViaFabricPlus is built for.

**Comment by yourfatherme** [comment]
for example
![image](https://github.com/FlorianMichael/ViaForge/assets/95916137/d7cd16dd-77b7-404b-bfcd-98cc3f05fb54)

**Comment by FlorianMichael** [comment]
I think LiquidBounce fixed this if you install ViaForge over the LiquidLauncher
