### ISSUE TITLE
Can't connect 1.16+ servers with 1.8.9 ViaForge

### ISSUE THREAD

**Issue by Aspw-w** [ViaVersion/ViaForge#64]
I tried Debug with Idea and Test with Build, but I got this error in both. Protocols below 1.15.2 work normally.
Also, the GuiProtocolSelector versions are inconsistent, does this have anything to do with it?
![image1](https://github.com/ViaVersion/ViaForge/assets/75427057/3921d86f-9bda-40a2-9caf-99cf282755d2)
![image](https://github.com/ViaVersion/ViaForge/assets/75427057/073ef599-22c4-40ff-b049-cc2b4fb39f2a)

**Comment by FlorianMichael** [comment]
Please report this issue to ViaBackwards with more Information like the server you are trying to connecting to

**Comment by Aspw-w** [comment]
ok

**Comment by FlorianMichael** [comment]
Can you try the latest version of ViaForge and if it doesn't work try it without any other mods?

**Comment by Kichura** [comment]
Closing this issue as it was transferred to viabackwards.
