### ISSUE TITLE
About ViaVersion_MovementThreshold

### ISSUE THREAD

**Issue by FengXiaoSkidGod** [ViaVersion/ViaForge#66]
@ModifyConstant(method = "onLivingUpdate", constant = @Constant(doubleValue = 0.005D))
    private double ViaVersion_MovementThreshold(double constant) {
        final ViaVersionFix viaversionfix = (ViaVersionFix) LiquidBounce.moduleManager.getModule(ViaVersionFix.class);
        if (Objects.requireNonNull(viaversionfix.getState())){
            return 0.003D;
        }
        return 0.005D;
    }
I got a null pointer error, I want to know if ViaVersion_MovementThreshold existed in ViaForge

**Comment by FengXiaoSkidGod** [comment]
Or an older version?

**Comment by FlorianMichael** [comment]
This code and the ViaVersionFix class is not part of the ViaForge codebase at all

**Comment by FengXiaoSkidGod** [comment]
ok
