### ISSUE TITLE
ViaForge cannot connect to a server

### ISSUE THREAD

**Issue by xthebombx** [ViaVersion/ViaForge#78]
### General Information

ViaForge refuses to connect no matter what but the server works for ANYTHING else. Which is confusing..

Failed to connect to the server: Internal Exception: io.netty.handler.codec.DecoderException: Java.io.I0Exception: Bad packet id: 25

### Bug Description

Failed to connect to the server
Internal Exception: io.netty.handler.codec.DecoderException: Java.io.I0Exception: Bad packet id
25

### Steps to Reproduce

Open client. 
Click minecraft server
click connect.
wait for a while
**_pain._** (Failed to connect to the server Internal Exception: io.netty.handler.codec.DecoderException: Java.io.I0Exception: Bad packet id 25)

### Expected Behavior

Just join the mf server the first time XD

**Comment by FlorianMichael** [comment]
Please provide all important information:
Which version is the client?
Which version is the server?
Which version do you have set in the GUI?
Have you installed other mods, if so, uninstall them all, does the error still occur?
ViaVersion dump?
Do you have the latest ViaForge version of the GH Actions?

**Comment by xthebombx** [comment]
I got you

The actual version of the client is 1.8.9
The version of the server is 1.19.2
The GUI is 1.19.1/2

I do not have any other mods other than that and where can I find the ViaVersion dump at? I can try to redownload the latest version but other than that I have no clue

**Comment by FlorianMichael** [comment]
What type of software is the server using? If it's Vanilla/Spigot/Paper does the server have secure profile enforcing enabled? If so, that's currently not supported. If the server is a Forge/Fabric server, joining these server softwares is also not supported.

**Comment by xthebombx** [comment]
Problem solved: Secure Profiles Enabled = Pain and cant do anything about it (Closing Ticket message)
