### ISSUE TITLE
ViaForge 1.8.9 broken

### ISSUE THREAD

**Issue by Aspw-w** [ViaVersion/ViaForge#84]
### General Information

ViaForge 1.8.9 not working in latest viaversion pre builds (4.10.0-24w09a-SNAPSHOT)

### Bug Description

https://mclo.gs/ndFub9k

### Steps to Reproduce

1. switch to viaversion higher than 1.8
2. join server

### Expected Behavior

join server with viaversion

**Comment by FlorianMichael** [comment]
ViaRewind dev version needs updating, will do that later

**Comment by Aspw-w** [comment]
ok. thx
